#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from exercicio3.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "exercicio3.y"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

typedef struct ast Ast;

typedef enum {
    DADO_INTEIRO,
    DADO_REAL,
    DADO_TEXTO
} TipoDado;

extern FILE *yyin;
int yylex(void);
void yyerror(const char *s);

// AST - Arvore de Sintaxe Abstrata

typedef enum {
    NODE_NUM,
    NODE_STRING,
    NODE_BK,

    NODE_VAR_VALUE,
    NODE_ARRAY_VALUE,

    NODE_SOMA,
    NODE_SUB,
    NODE_MULT,
    NODE_DIV,
    NODE_POT,
    NODE_NEG,

    NODE_MAIOR,
    NODE_MENOR,
    NODE_MAIOR_IGUAL,
    NODE_MENOR_IGUAL,
    NODE_IGUAL,
    NODE_DIFERENTE,
    NODE_AND,
    NODE_OR,
    NODE_NOT,

    NODE_DECL,
    NODE_DECL_ARRAY,
    NODE_ASSIGN,
    NODE_ASSIGN_ARRAY,
    NODE_READ,
    NODE_READ_ARRAY,
    NODE_PRINT,
    NODE_PRINT_LIST,
    NODE_BLOCK,
    NODE_IF,
    NODE_WHEN,
    NODE_DO_WHEN
} NodeType;

struct ast {
    NodeType tipo;
    TipoDado dado_tipo;
    struct ast *esq;
    struct ast *dir;
    struct ast *terceiro;
    double valor;
    char nome[100];
    char texto[512];
};

typedef struct valor {
    TipoDado tipo;
    double num;
    char *str;
} Valor;

typedef struct simbolo {
    char nome[100];
    TipoDado tipo;
    int eh_vetor;
    int tamanho;
    int inicializado;
    double num_valor;
    char *str_valor;
    double *num_vetor;
    char **str_vetor;
    struct simbolo *prox;
} Simbolo;

Simbolo *tabela = NULL;

Ast *novo_no(NodeType tipo, Ast *esq, Ast *dir);
Ast *novo_num(double valor);
Ast *novo_string(char *texto_com_aspas);
Ast *novo_bk(void);
Ast *novo_var_value(char *nome);
Ast *novo_array_value(char *nome, Ast *indice);
Ast *novo_decl(TipoDado tipo, char *nome);
Ast *novo_decl_array(TipoDado tipo, char *nome, Ast *tamanho);
void aplicar_tipo_declaracao(Ast *a, TipoDado tipo);
Ast *novo_assign(char *nome, Ast *valor);
Ast *novo_assign_array(char *nome, Ast *indice, Ast *valor);
Ast *novo_read(char *nome);
Ast *novo_read_array(char *nome, Ast *indice);
Ast *novo_print(Ast *lista);
Ast *novo_print_list(Ast *lista, Ast *item);
Ast *novo_if(Ast *cond, Ast *bloco_true, Ast *bloco_false);
Ast *novo_when(Ast *cond, Ast *bloco);
Ast *novo_do_when(Ast *bloco, Ast *cond);
Ast *novo_cmp(int op, Ast *esq, Ast *dir);

Valor eval(Ast *a);
void executar(Ast *a);
void liberar_ast(Ast *a);
int verdade(Valor v);
int print_itens(Ast *a);

char *duplicar_string(const char *s);
void remover_aspas(char *destino, const char *origem, int max);
const char *nome_tipo(TipoDado tipo);

Simbolo *buscar_simbolo(const char *nome);
Simbolo *criar_simbolo(const char *nome, TipoDado tipo, int eh_vetor);
void declarar_variavel(TipoDado tipo, const char *nome);
void declarar_vetor(TipoDado tipo, const char *nome, Ast *tamanho_ast);
void atribuir_variavel(const char *nome, Valor v);
void atribuir_vetor(const char *nome, Ast *indice_ast, Valor v);
Valor valor_variavel(const char *nome);
Valor valor_vetor(const char *nome, Ast *indice_ast);
void ler_variavel(const char *nome);
void ler_vetor(const char *nome, Ast *indice_ast);
int indice_valido(Simbolo *s, Ast *indice_ast);
Valor valor_num(double n);
Valor valor_str(char *s);


#line 138 "exercicio3.y"
typedef union {
    double real;
    int op_log;
    char str[512];
    Ast *a;
    TipoDado tipo;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NUM	258
#define	CMP	259
#define	VAR_NAME	260
#define	TXT	261
#define	INICIO	262
#define	FIM	263
#define	TIPO_INTEIRO	264
#define	TIPO_REAL	265
#define	TIPO_TEXTO	266
#define	OUT	267
#define	IN	268
#define	IF	269
#define	ELSE	270
#define	WHEN	271
#define	DO	272
#define	AND	273
#define	OR	274
#define	NOT	275
#define	BK	276
#define	NEG	277


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NUM;
static const int CMP;
static const int VAR_NAME;
static const int TXT;
static const int INICIO;
static const int FIM;
static const int TIPO_INTEIRO;
static const int TIPO_REAL;
static const int TIPO_TEXTO;
static const int OUT;
static const int IN;
static const int IF;
static const int ELSE;
static const int WHEN;
static const int DO;
static const int AND;
static const int OR;
static const int NOT;
static const int BK;
static const int NEG;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NUM=258
	,CMP=259
	,VAR_NAME=260
	,TXT=261
	,INICIO=262
	,FIM=263
	,TIPO_INTEIRO=264
	,TIPO_REAL=265
	,TIPO_TEXTO=266
	,OUT=267
	,IN=268
	,IF=269
	,ELSE=270
	,WHEN=271
	,DO=272
	,AND=273
	,OR=274
	,NOT=275
	,BK=276
	,NEG=277


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NUM=258;
const int YY_parse_CLASS::CMP=259;
const int YY_parse_CLASS::VAR_NAME=260;
const int YY_parse_CLASS::TXT=261;
const int YY_parse_CLASS::INICIO=262;
const int YY_parse_CLASS::FIM=263;
const int YY_parse_CLASS::TIPO_INTEIRO=264;
const int YY_parse_CLASS::TIPO_REAL=265;
const int YY_parse_CLASS::TIPO_TEXTO=266;
const int YY_parse_CLASS::OUT=267;
const int YY_parse_CLASS::IN=268;
const int YY_parse_CLASS::IF=269;
const int YY_parse_CLASS::ELSE=270;
const int YY_parse_CLASS::WHEN=271;
const int YY_parse_CLASS::DO=272;
const int YY_parse_CLASS::AND=273;
const int YY_parse_CLASS::OR=274;
const int YY_parse_CLASS::NOT=275;
const int YY_parse_CLASS::BK=276;
const int YY_parse_CLASS::NEG=277;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		116
#define	YYFLAG		-32768
#define	YYNTBASE	37

#define YYTRANSLATE(x) ((unsigned)(x) <= 277 ? yytranslate[x] : 55)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    33,
    34,    24,    22,    29,    23,     2,    25,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    28,     2,
    30,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    31,     2,    32,    27,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    35,     2,    36,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    26
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     4,     6,     9,    11,    14,    17,    20,    23,    25,
    27,    29,    30,    32,    34,    36,    39,    43,    45,    47,
    51,    56,    60,    67,    69,    74,    76,    81,    86,    90,
    92,    94,    96,   104,   116,   124,   134,   138,   142,   146,
   150,   154,   157,   160,   164,   168,   172,   176,   178,   180,
   182
};

static const short yyrhs[] = {     7,
    38,     8,     0,    38,     0,    38,    39,     0,    39,     0,
    42,    40,     0,    45,    40,     0,    47,    40,     0,    49,
    40,     0,    52,     0,    53,     0,    28,     0,     0,     9,
     0,    10,     0,    11,     0,    41,    43,     0,    43,    29,
    44,     0,    44,     0,     5,     0,     5,    30,    46,     0,
     5,    31,    54,    32,     0,     5,    30,    46,     0,     5,
    31,    54,    32,    30,    46,     0,    54,     0,    13,    33,
    48,    34,     0,     5,     0,     5,    31,    54,    32,     0,
    12,    33,    50,    34,     0,    50,    29,    51,     0,    51,
     0,    54,     0,    21,     0,    14,    33,    54,    34,    35,
    38,    36,     0,    14,    33,    54,    34,    35,    38,    36,
    15,    35,    38,    36,     0,    16,    33,    54,    34,    35,
    38,    36,     0,    17,    35,    38,    36,    16,    33,    54,
    34,    40,     0,    54,    22,    54,     0,    54,    23,    54,
     0,    54,    24,    54,     0,    54,    25,    54,     0,    54,
    27,    54,     0,    23,    54,     0,    20,    54,     0,    54,
    18,    54,     0,    54,    19,    54,     0,    54,     4,    54,
     0,    33,    54,    34,     0,     3,     0,     6,     0,     5,
     0,     5,    31,    54,    32,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   172,   177,   183,   187,   192,   194,   195,   196,   197,   198,
   201,   203,   206,   208,   209,   212,   219,   223,   228,   232,
   235,   240,   244,   249,   253,   257,   259,   262,   266,   268,
   271,   273,   276,   280,   285,   289,   294,   296,   297,   298,
   299,   300,   301,   302,   303,   304,   305,   306,   307,   308,
   309
};

static const char * const yytname[] = {   "$","error","$illegal.","NUM","CMP",
"VAR_NAME","TXT","INICIO","FIM","TIPO_INTEIRO","TIPO_REAL","TIPO_TEXTO","OUT",
"IN","IF","ELSE","WHEN","DO","AND","OR","NOT","BK","'+'","'-'","'*'","'/'","NEG",
"'^'","';'","','","'='","'['","']'","'('","')'","'{'","'}'","programa","lista_comandos",
"comando","fimcmd","tipo","declaracao","lista_declaradores","declarador","atribuicao",
"valor_atribuicao","leitura","destino_leitura","escrita","lista_print","item_print",
"condicional","repeticao","expr",""
};
#endif

static const short yyr1[] = {     0,
    37,    37,    38,    38,    39,    39,    39,    39,    39,    39,
    40,    40,    41,    41,    41,    42,    43,    43,    44,    44,
    44,    45,    45,    46,    47,    48,    48,    49,    50,    50,
    51,    51,    52,    52,    53,    53,    54,    54,    54,    54,
    54,    54,    54,    54,    54,    54,    54,    54,    54,    54,
    54
};

static const short yyr2[] = {     0,
     3,     1,     2,     1,     2,     2,     2,     2,     1,     1,
     1,     0,     1,     1,     1,     2,     3,     1,     1,     3,
     4,     3,     6,     1,     4,     1,     4,     4,     3,     1,
     1,     1,     7,    11,     7,     9,     3,     3,     3,     3,
     3,     2,     2,     3,     3,     3,     3,     1,     1,     1,
     4
};

static const short yydefact[] = {     0,
     0,     0,    13,    14,    15,     0,     0,     0,     0,     0,
     2,     4,     0,    12,    12,    12,    12,     9,    10,     0,
     0,     0,     0,     0,     0,     0,     0,     3,    19,    16,
    18,    11,     5,     6,     7,     8,    48,    50,    49,     0,
     0,     0,    22,    24,     0,     1,    32,     0,    30,    31,
    26,     0,     0,     0,     0,     0,     0,     0,     0,    43,
    42,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    28,     0,    25,     0,     0,     0,    20,     0,
    17,     0,    47,    46,    44,    45,    37,    38,    39,    40,
    41,     0,    29,     0,     0,     0,     0,    21,    51,    23,
    27,     0,     0,     0,    33,    35,     0,     0,    12,     0,
    36,     0,    34,     0,     0,     0
};

static const short yydefgoto[] = {   114,
    11,    12,    33,    13,    14,    30,    31,    15,    43,    16,
    52,    17,    48,    49,    18,    19,    44
};

static const short yypact[] = {   272,
     0,   292,-32768,-32768,-32768,   -31,   -22,   -17,   -14,    -3,
   292,-32768,    31,    14,    14,    14,    14,-32768,-32768,   184,
   184,   282,   162,    40,   184,   184,   292,-32768,    42,    18,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,    29,-32768,   184,
   184,   184,-32768,    16,   174,-32768,-32768,   -20,-32768,    16,
    37,    15,    -1,   126,    53,   184,   184,    31,   184,    47,
    47,   139,   184,   184,   184,   184,   184,   184,   184,   184,
    51,   162,-32768,   184,-32768,    55,    57,    70,-32768,   196,
-32768,   207,-32768,   240,   251,   229,    60,    60,    47,    47,
    47,   184,-32768,   218,   292,   292,    64,-32768,-32768,-32768,
-32768,    66,   101,   184,    73,-32768,   152,    63,    14,   292,
-32768,   111,-32768,   100,   103,-32768
};

static const short yypgoto[] = {-32768,
    -2,    -7,   -10,-32768,-32768,-32768,    43,-32768,   -55,-32768,
-32768,-32768,-32768,    32,-32768,-32768,   -13
};


#define	YYLAST		309


static const short yytable[] = {    22,
    79,    23,    63,    28,    34,    35,    36,    45,    72,    50,
    24,    53,    54,    73,    28,    25,    64,    65,    26,    63,
    66,    67,    68,    69,    55,    70,    60,    61,    62,    20,
    21,    27,    76,    64,    65,    29,   100,    66,    67,    68,
    69,    32,    70,    80,    51,    82,    58,    28,    75,    84,
    85,    86,    87,    88,    89,    90,    91,     1,    50,    59,
    94,     3,     4,     5,     6,     7,     8,    74,     9,    10,
     1,    56,    57,    70,     3,     4,     5,     6,     7,     8,
    92,     9,    10,    68,    69,    97,    70,   108,    78,    95,
   107,    96,   102,   103,    28,    28,   104,   110,   111,   115,
    81,   105,   116,    93,    28,     1,     0,   112,     0,     3,
     4,     5,     6,     7,     8,     1,     9,    10,     0,     3,
     4,     5,     6,     7,     8,     0,     9,    10,     0,    63,
     0,     0,     0,     0,     0,     0,   106,     0,     0,     0,
     0,     0,    63,    64,    65,     0,   113,    66,    67,    68,
    69,     0,    70,     0,     0,    63,    64,    65,     0,    77,
    66,    67,    68,    69,    37,    70,    38,    39,     0,    64,
    65,     0,    83,    66,    67,    68,    69,    63,    70,     0,
     0,    40,    47,     0,    41,   109,    37,     0,    38,    39,
     0,    64,    65,     0,    42,    66,    67,    68,    69,    63,
    70,     0,     0,    40,     0,    71,    41,     0,     0,     0,
    63,     0,     0,    64,    65,     0,    42,    66,    67,    68,
    69,    63,    70,     0,    64,    65,     0,    98,    66,    67,
    68,    69,    63,    70,     0,    64,    65,     0,    99,    66,
    67,    68,    69,-32768,    70,     0,    64,     0,     0,   101,
    66,    67,    68,    69,    63,    70,     0,     0,     0,     0,
     0,    66,    67,    68,    69,     0,    70,     0,     0,     0,
     0,     0,    66,    67,    68,    69,     1,    70,     2,     0,
     3,     4,     5,     6,     7,     8,     1,     9,    10,    46,
     3,     4,     5,     6,     7,     8,     1,     9,    10,     0,
     3,     4,     5,     6,     7,     8,     0,     9,    10
};

static const short yycheck[] = {     2,
    56,    33,     4,    11,    15,    16,    17,    21,    29,    23,
    33,    25,    26,    34,    22,    33,    18,    19,    33,     4,
    22,    23,    24,    25,    27,    27,    40,    41,    42,    30,
    31,    35,    34,    18,    19,     5,    92,    22,    23,    24,
    25,    28,    27,    57,     5,    59,    29,    55,    34,    63,
    64,    65,    66,    67,    68,    69,    70,     5,    72,    31,
    74,     9,    10,    11,    12,    13,    14,    31,    16,    17,
     5,    30,    31,    27,     9,    10,    11,    12,    13,    14,
    30,    16,    17,    24,    25,    16,    27,    15,    36,    35,
   104,    35,    95,    96,   102,   103,    33,    35,   109,     0,
    58,    36,     0,    72,   112,     5,    -1,   110,    -1,     9,
    10,    11,    12,    13,    14,     5,    16,    17,    -1,     9,
    10,    11,    12,    13,    14,    -1,    16,    17,    -1,     4,
    -1,    -1,    -1,    -1,    -1,    -1,    36,    -1,    -1,    -1,
    -1,    -1,     4,    18,    19,    -1,    36,    22,    23,    24,
    25,    -1,    27,    -1,    -1,     4,    18,    19,    -1,    34,
    22,    23,    24,    25,     3,    27,     5,     6,    -1,    18,
    19,    -1,    34,    22,    23,    24,    25,     4,    27,    -1,
    -1,    20,    21,    -1,    23,    34,     3,    -1,     5,     6,
    -1,    18,    19,    -1,    33,    22,    23,    24,    25,     4,
    27,    -1,    -1,    20,    -1,    32,    23,    -1,    -1,    -1,
     4,    -1,    -1,    18,    19,    -1,    33,    22,    23,    24,
    25,     4,    27,    -1,    18,    19,    -1,    32,    22,    23,
    24,    25,     4,    27,    -1,    18,    19,    -1,    32,    22,
    23,    24,    25,     4,    27,    -1,    18,    -1,    -1,    32,
    22,    23,    24,    25,     4,    27,    -1,    -1,    -1,    -1,
    -1,    22,    23,    24,    25,    -1,    27,    -1,    -1,    -1,
    -1,    -1,    22,    23,    24,    25,     5,    27,     7,    -1,
     9,    10,    11,    12,    13,    14,     5,    16,    17,     8,
     9,    10,    11,    12,    13,    14,     5,    16,    17,    -1,
     9,    10,    11,    12,    13,    14,    -1,    16,    17
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 173 "exercicio3.y"
{
          executar(yyvsp[-1].a);
          liberar_ast(yyvsp[-1].a);
      ;
    break;}
case 2:
#line 177 "exercicio3.y"
{
          executar(yyvsp[0].a);
          liberar_ast(yyvsp[0].a);
      ;
    break;}
case 3:
#line 184 "exercicio3.y"
{
          yyval.a = novo_no(NODE_BLOCK, yyvsp[-1].a, yyvsp[0].a);
      ;
    break;}
case 4:
#line 187 "exercicio3.y"
{
          yyval.a = yyvsp[0].a;
      ;
    break;}
case 5:
#line 193 "exercicio3.y"
{ yyval.a = yyvsp[-1].a; ;
    break;}
case 6:
#line 194 "exercicio3.y"
{ yyval.a = yyvsp[-1].a; ;
    break;}
case 7:
#line 195 "exercicio3.y"
{ yyval.a = yyvsp[-1].a; ;
    break;}
case 8:
#line 196 "exercicio3.y"
{ yyval.a = yyvsp[-1].a; ;
    break;}
case 9:
#line 197 "exercicio3.y"
{ yyval.a = yyvsp[0].a; ;
    break;}
case 10:
#line 198 "exercicio3.y"
{ yyval.a = yyvsp[0].a; ;
    break;}
case 13:
#line 207 "exercicio3.y"
{ yyval.tipo = DADO_INTEIRO; ;
    break;}
case 14:
#line 208 "exercicio3.y"
{ yyval.tipo = DADO_REAL; ;
    break;}
case 15:
#line 209 "exercicio3.y"
{ yyval.tipo = DADO_TEXTO; ;
    break;}
case 16:
#line 213 "exercicio3.y"
{
          aplicar_tipo_declaracao(yyvsp[0].a, yyvsp[-1].tipo);
          yyval.a = yyvsp[0].a;
      ;
    break;}
case 17:
#line 220 "exercicio3.y"
{
          yyval.a = novo_no(NODE_BLOCK, yyvsp[-2].a, yyvsp[0].a);
      ;
    break;}
case 18:
#line 223 "exercicio3.y"
{
          yyval.a = yyvsp[0].a;
      ;
    break;}
case 19:
#line 229 "exercicio3.y"
{
          yyval.a = novo_decl(DADO_REAL, yyvsp[0].str);
      ;
    break;}
case 20:
#line 232 "exercicio3.y"
{
          yyval.a = novo_no(NODE_BLOCK, novo_decl(DADO_REAL, yyvsp[-2].str), novo_assign(yyvsp[-2].str, yyvsp[0].a));
      ;
    break;}
case 21:
#line 235 "exercicio3.y"
{
          yyval.a = novo_decl_array(DADO_REAL, yyvsp[-3].str, yyvsp[-1].a);
      ;
    break;}
case 22:
#line 241 "exercicio3.y"
{
          yyval.a = novo_assign(yyvsp[-2].str, yyvsp[0].a);
      ;
    break;}
case 23:
#line 244 "exercicio3.y"
{
          yyval.a = novo_assign_array(yyvsp[-5].str, yyvsp[-3].a, yyvsp[0].a);
      ;
    break;}
case 24:
#line 250 "exercicio3.y"
{ yyval.a = yyvsp[0].a; ;
    break;}
case 25:
#line 254 "exercicio3.y"
{ yyval.a = yyvsp[-1].a; ;
    break;}
case 26:
#line 258 "exercicio3.y"
{ yyval.a = novo_read(yyvsp[0].str); ;
    break;}
case 27:
#line 259 "exercicio3.y"
{ yyval.a = novo_read_array(yyvsp[-3].str, yyvsp[-1].a); ;
    break;}
case 28:
#line 263 "exercicio3.y"
{ yyval.a = novo_print(yyvsp[-1].a); ;
    break;}
case 29:
#line 267 "exercicio3.y"
{ yyval.a = novo_print_list(yyvsp[-2].a, yyvsp[0].a); ;
    break;}
case 30:
#line 268 "exercicio3.y"
{ yyval.a = yyvsp[0].a; ;
    break;}
case 31:
#line 272 "exercicio3.y"
{ yyval.a = yyvsp[0].a; ;
    break;}
case 32:
#line 273 "exercicio3.y"
{ yyval.a = novo_bk(); ;
    break;}
case 33:
#line 277 "exercicio3.y"
{
          yyval.a = novo_if(yyvsp[-4].a, yyvsp[-1].a, NULL);
      ;
    break;}
case 34:
#line 280 "exercicio3.y"
{
          yyval.a = novo_if(yyvsp[-8].a, yyvsp[-5].a, yyvsp[-1].a);
      ;
    break;}
case 35:
#line 286 "exercicio3.y"
{
          yyval.a = novo_when(yyvsp[-4].a, yyvsp[-1].a);
      ;
    break;}
case 36:
#line 289 "exercicio3.y"
{
          yyval.a = novo_do_when(yyvsp[-6].a, yyvsp[-2].a);
      ;
    break;}
case 37:
#line 295 "exercicio3.y"
{ yyval.a = novo_no(NODE_SOMA, yyvsp[-2].a, yyvsp[0].a); ;
    break;}
case 38:
#line 296 "exercicio3.y"
{ yyval.a = novo_no(NODE_SUB, yyvsp[-2].a, yyvsp[0].a); ;
    break;}
case 39:
#line 297 "exercicio3.y"
{ yyval.a = novo_no(NODE_MULT, yyvsp[-2].a, yyvsp[0].a); ;
    break;}
case 40:
#line 298 "exercicio3.y"
{ yyval.a = novo_no(NODE_DIV, yyvsp[-2].a, yyvsp[0].a); ;
    break;}
case 41:
#line 299 "exercicio3.y"
{ yyval.a = novo_no(NODE_POT, yyvsp[-2].a, yyvsp[0].a); ;
    break;}
case 42:
#line 300 "exercicio3.y"
{ yyval.a = novo_no(NODE_NEG, yyvsp[0].a, NULL); ;
    break;}
case 43:
#line 301 "exercicio3.y"
{ yyval.a = novo_no(NODE_NOT, yyvsp[0].a, NULL); ;
    break;}
case 44:
#line 302 "exercicio3.y"
{ yyval.a = novo_no(NODE_AND, yyvsp[-2].a, yyvsp[0].a); ;
    break;}
case 45:
#line 303 "exercicio3.y"
{ yyval.a = novo_no(NODE_OR, yyvsp[-2].a, yyvsp[0].a); ;
    break;}
case 46:
#line 304 "exercicio3.y"
{ yyval.a = novo_cmp(yyvsp[-1].op_log, yyvsp[-2].a, yyvsp[0].a); ;
    break;}
case 47:
#line 305 "exercicio3.y"
{ yyval.a = yyvsp[-1].a; ;
    break;}
case 48:
#line 306 "exercicio3.y"
{ yyval.a = novo_num(yyvsp[0].real); ;
    break;}
case 49:
#line 307 "exercicio3.y"
{ yyval.a = novo_string(yyvsp[0].str); ;
    break;}
case 50:
#line 308 "exercicio3.y"
{ yyval.a = novo_var_value(yyvsp[0].str); ;
    break;}
case 51:
#line 309 "exercicio3.y"
{ yyval.a = novo_array_value(yyvsp[-3].str, yyvsp[-1].a); ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 312 "exercicio3.y"


#include "lex.yy.c"

void yyerror(const char *s) {
    printf("Erro sintatico: %s\n", s);
}

Valor valor_num(double n) {
    Valor v;
    v.tipo = DADO_REAL;
    v.num = n;
    v.str = NULL;
    return v;
}

Valor valor_str(char *s) {
    Valor v;
    v.tipo = DADO_TEXTO;
    v.num = 0;
    v.str = s;
    return v;
}

char *duplicar_string(const char *s) {
    char *nova;

    if (s == NULL) {
        s = "";
    }

    nova = malloc(strlen(s) + 1);
    if (nova == NULL) {
        printf("Erro de memoria ao duplicar string.\n");
        exit(1);
    }

    strcpy(nova, s);
    return nova;
}

void remover_aspas(char *destino, const char *origem, int max) {
    int tam, inicio, fim, qtd;

    if (origem == NULL) {
        destino[0] = '\0';
        return;
    }

    tam = strlen(origem);
    inicio = 0;
    fim = tam;

    if (tam >= 2 && origem[0] == '"' && origem[tam - 1] == '"') {
        inicio = 1;
        fim = tam - 1;
    }

    qtd = fim - inicio;
    if (qtd >= max) {
        qtd = max - 1;
    }

    strncpy(destino, origem + inicio, qtd);
    destino[qtd] = '\0';
}

const char *nome_tipo(TipoDado tipo) {
    switch (tipo) {
        case DADO_INTEIRO: return "inteiro";
        case DADO_REAL: return "real";
        case DADO_TEXTO: return "texto";
    }
    return "desconhecido";
}

Ast *novo_no(NodeType tipo, Ast *esq, Ast *dir) {
    Ast *novo = malloc(sizeof(Ast));

    if (novo == NULL) {
        printf("Erro de memoria ao criar no da AST.\n");
        exit(1);
    }

    novo->tipo = tipo;
    novo->dado_tipo = DADO_REAL;
    novo->esq = esq;
    novo->dir = dir;
    novo->terceiro = NULL;
    novo->valor = 0;
    novo->nome[0] = '\0';
    novo->texto[0] = '\0';

    return novo;
}

Ast *novo_num(double valor) {
    Ast *novo = novo_no(NODE_NUM, NULL, NULL);
    novo->valor = valor;
    return novo;
}

Ast *novo_string(char *texto_com_aspas) {
    Ast *novo = novo_no(NODE_STRING, NULL, NULL);
    remover_aspas(novo->texto, texto_com_aspas, 512);
    return novo;
}

Ast *novo_bk(void) {
    return novo_no(NODE_BK, NULL, NULL);
}

Ast *novo_var_value(char *nome) {
    Ast *novo = novo_no(NODE_VAR_VALUE, NULL, NULL);
    strncpy(novo->nome, nome, 99);
    novo->nome[99] = '\0';
    return novo;
}

Ast *novo_array_value(char *nome, Ast *indice) {
    Ast *novo = novo_no(NODE_ARRAY_VALUE, indice, NULL);
    strncpy(novo->nome, nome, 99);
    novo->nome[99] = '\0';
    return novo;
}

Ast *novo_decl(TipoDado tipo, char *nome) {
    Ast *novo = novo_no(NODE_DECL, NULL, NULL);
    novo->dado_tipo = tipo;
    strncpy(novo->nome, nome, 99);
    novo->nome[99] = '\0';
    return novo;
}

Ast *novo_decl_array(TipoDado tipo, char *nome, Ast *tamanho) {
    Ast *novo = novo_no(NODE_DECL_ARRAY, tamanho, NULL);
    novo->dado_tipo = tipo;
    strncpy(novo->nome, nome, 99);
    novo->nome[99] = '\0';
    return novo;
}

void aplicar_tipo_declaracao(Ast *a, TipoDado tipo) {
    if (a == NULL) {
        return;
    }

    if (a->tipo == NODE_DECL || a->tipo == NODE_DECL_ARRAY) {
        a->dado_tipo = tipo;
        return;
    }

    if (a->tipo == NODE_BLOCK) {
        aplicar_tipo_declaracao(a->esq, tipo);
        aplicar_tipo_declaracao(a->dir, tipo);
        aplicar_tipo_declaracao(a->terceiro, tipo);
    }
}

Ast *novo_assign(char *nome, Ast *valor) {
    Ast *novo = novo_no(NODE_ASSIGN, valor, NULL);
    strncpy(novo->nome, nome, 99);
    novo->nome[99] = '\0';
    return novo;
}

Ast *novo_assign_array(char *nome, Ast *indice, Ast *valor) {
    Ast *novo = novo_no(NODE_ASSIGN_ARRAY, indice, valor);
    strncpy(novo->nome, nome, 99);
    novo->nome[99] = '\0';
    return novo;
}

Ast *novo_read(char *nome) {
    Ast *novo = novo_no(NODE_READ, NULL, NULL);
    strncpy(novo->nome, nome, 99);
    novo->nome[99] = '\0';
    return novo;
}

Ast *novo_read_array(char *nome, Ast *indice) {
    Ast *novo = novo_no(NODE_READ_ARRAY, indice, NULL);
    strncpy(novo->nome, nome, 99);
    novo->nome[99] = '\0';
    return novo;
}

Ast *novo_print(Ast *lista) {
    return novo_no(NODE_PRINT, lista, NULL);
}

Ast *novo_print_list(Ast *lista, Ast *item) {
    return novo_no(NODE_PRINT_LIST, lista, item);
}

Ast *novo_if(Ast *cond, Ast *bloco_true, Ast *bloco_false) {
    Ast *novo = novo_no(NODE_IF, cond, bloco_true);
    novo->terceiro = bloco_false;
    return novo;
}

Ast *novo_when(Ast *cond, Ast *bloco) {
    return novo_no(NODE_WHEN, cond, bloco);
}

Ast *novo_do_when(Ast *bloco, Ast *cond) {
    return novo_no(NODE_DO_WHEN, bloco, cond);
}

Ast *novo_cmp(int op, Ast *esq, Ast *dir) {
    NodeType tipo;

    switch (op) {
        case 1: tipo = NODE_MAIOR; break;
        case 2: tipo = NODE_MENOR; break;
        case 3: tipo = NODE_MAIOR_IGUAL; break;
        case 4: tipo = NODE_MENOR_IGUAL; break;
        case 5: tipo = NODE_IGUAL; break;
        case 6: tipo = NODE_DIFERENTE; break;
        default: tipo = NODE_IGUAL; break;
    }

    return novo_no(tipo, esq, dir);
}

Simbolo *buscar_simbolo(const char *nome) {
    Simbolo *atual = tabela;

    while (atual != NULL) {
        if (strcmp(atual->nome, nome) == 0) {
            return atual;
        }
        atual = atual->prox;
    }

    return NULL;
}

Simbolo *criar_simbolo(const char *nome, TipoDado tipo, int eh_vetor) {
    Simbolo *s = malloc(sizeof(Simbolo));

    if (s == NULL) {
        printf("Erro de memoria ao criar simbolo.\n");
        exit(1);
    }

    strncpy(s->nome, nome, 99);
    s->nome[99] = '\0';
    s->tipo = tipo;
    s->eh_vetor = eh_vetor;
    s->tamanho = 0;
    s->inicializado = 0;
    s->num_valor = 0;
    s->str_valor = duplicar_string("");
    s->num_vetor = NULL;
    s->str_vetor = NULL;
    s->prox = tabela;
    tabela = s;

    return s;
}

void declarar_variavel(TipoDado tipo, const char *nome) {
    if (buscar_simbolo(nome) != NULL) {
        printf("Erro semantico: variavel '%s' ja declarada.\n", nome);
        return;
    }

    criar_simbolo(nome, tipo, 0);
}

void declarar_vetor(TipoDado tipo, const char *nome, Ast *tamanho_ast) {
    Valor tam_valor;
    int tamanho;
    Simbolo *s;
    int i;

    if (buscar_simbolo(nome) != NULL) {
        printf("Erro semantico: variavel '%s' ja declarada.\n", nome);
        return;
    }

    tam_valor = eval(tamanho_ast);

    if (tam_valor.tipo == DADO_TEXTO || floor(tam_valor.num) != tam_valor.num || tam_valor.num <= 0) {
        printf("Erro semantico: tamanho do vetor '%s' deve ser inteiro positivo.\n", nome);
        return;
    }

    tamanho = (int) tam_valor.num;
    s = criar_simbolo(nome, tipo, 1);
    s->tamanho = tamanho;
    s->inicializado = 1;

    if (tipo == DADO_TEXTO) {
        s->str_vetor = calloc(tamanho, sizeof(char *));
        if (s->str_vetor == NULL) {
            printf("Erro de memoria ao alocar vetor de texto '%s'.\n", nome);
            exit(1);
        }
        for (i = 0; i < tamanho; i++) {
            s->str_vetor[i] = duplicar_string("");
        }
    } else {
        s->num_vetor = calloc(tamanho, sizeof(double));
        if (s->num_vetor == NULL) {
            printf("Erro de memoria ao alocar vetor numerico '%s'.\n", nome);
            exit(1);
        }
    }

    printf("Vetor '%s' alocado dinamicamente com %d posicoes.\n", nome, tamanho);
}

void atribuir_variavel(const char *nome, Valor v) {
    Simbolo *s = buscar_simbolo(nome);

    if (s == NULL) {
        printf("Erro semantico: variavel '%s' nao declarada.\n", nome);
        return;
    }

    if (s->eh_vetor) {
        printf("Erro semantico: '%s' e vetor. Use indice, exemplo: %s[0].\n", nome, nome);
        return;
    }

    if (s->tipo == DADO_TEXTO) {
        if (v.tipo != DADO_TEXTO) {
            printf("Erro semantico: variavel de texto '%s' precisa receber texto.\n", nome);
            return;
        }
        free(s->str_valor);
        s->str_valor = duplicar_string(v.str);
    } else {
        if (v.tipo == DADO_TEXTO) {
            printf("Erro semantico: variavel numerica '%s' nao pode receber texto.\n", nome);
            return;
        }

        if (s->tipo == DADO_INTEIRO) {
            s->num_valor = (int) v.num;
        } else {
            s->num_valor = v.num;
        }
    }

    s->inicializado = 1;
}

int indice_valido(Simbolo *s, Ast *indice_ast) {
    Valor indice_valor;
    int indice;

    indice_valor = eval(indice_ast);

    if (indice_valor.tipo == DADO_TEXTO || floor(indice_valor.num) != indice_valor.num) {
        printf("Erro semantico: indice do vetor '%s' deve ser inteiro.\n", s->nome);
        return -1;
    }

    indice = (int) indice_valor.num;

    if (indice < 0 || indice >= s->tamanho) {
        printf("Erro semantico: indice %d fora do limite do vetor '%s' de tamanho %d.\n", indice, s->nome, s->tamanho);
        return -1;
    }

    return indice;
}

void atribuir_vetor(const char *nome, Ast *indice_ast, Valor v) {
    Simbolo *s = buscar_simbolo(nome);
    int indice;

    if (s == NULL) {
        printf("Erro semantico: vetor '%s' nao declarado.\n", nome);
        return;
    }

    if (!s->eh_vetor) {
        printf("Erro semantico: '%s' nao e vetor.\n", nome);
        return;
    }

    indice = indice_valido(s, indice_ast);
    if (indice < 0) {
        return;
    }

    if (s->tipo == DADO_TEXTO) {
        if (v.tipo != DADO_TEXTO) {
            printf("Erro semantico: vetor de texto '%s' precisa receber texto.\n", nome);
            return;
        }
        free(s->str_vetor[indice]);
        s->str_vetor[indice] = duplicar_string(v.str);
    } else {
        if (v.tipo == DADO_TEXTO) {
            printf("Erro semantico: vetor numerico '%s' nao pode receber texto.\n", nome);
            return;
        }
        if (s->tipo == DADO_INTEIRO) {
            s->num_vetor[indice] = (int) v.num;
        } else {
            s->num_vetor[indice] = v.num;
        }
    }
}

Valor valor_variavel(const char *nome) {
    Simbolo *s = buscar_simbolo(nome);

    if (s == NULL) {
        printf("Erro semantico: variavel '%s' nao declarada.\n", nome);
        return valor_num(0);
    }

    if (s->eh_vetor) {
        printf("Erro semantico: '%s' e vetor. Use indice, exemplo: %s[0].\n", nome, nome);
        return valor_num(0);
    }

    if (!s->inicializado) {
        printf("Aviso semantico: variavel '%s' usada sem valor inicial.\n", nome);
    }

    if (s->tipo == DADO_TEXTO) {
        return valor_str(s->str_valor);
    }

    return valor_num(s->num_valor);
}

Valor valor_vetor(const char *nome, Ast *indice_ast) {
    Simbolo *s = buscar_simbolo(nome);
    int indice;

    if (s == NULL) {
        printf("Erro semantico: vetor '%s' nao declarado.\n", nome);
        return valor_num(0);
    }

    if (!s->eh_vetor) {
        printf("Erro semantico: '%s' nao e vetor.\n", nome);
        return valor_num(0);
    }

    indice = indice_valido(s, indice_ast);
    if (indice < 0) {
        return valor_num(0);
    }

    if (s->tipo == DADO_TEXTO) {
        return valor_str(s->str_vetor[indice]);
    }

    return valor_num(s->num_vetor[indice]);
}

void ler_variavel(const char *nome) {
    Simbolo *s = buscar_simbolo(nome);
    char buffer[512];
    double valor;

    if (s == NULL) {
        printf("Erro semantico: variavel '%s' nao declarada.\n", nome);
        return;
    }

    if (s->eh_vetor) {
        printf("Erro semantico: '%s' e vetor. Use indice na leitura.\n", nome);
        return;
    }

    printf("Digite valor para %s: ", nome);

    if (s->tipo == DADO_TEXTO) {
        scanf(" %511[^\n]", buffer);
        free(s->str_valor);
        s->str_valor = duplicar_string(buffer);
    } else {
        scanf(" %lf", &valor);
        if (s->tipo == DADO_INTEIRO) {
            s->num_valor = (int) valor;
        } else {
            s->num_valor = valor;
        }
    }

    s->inicializado = 1;
}

void ler_vetor(const char *nome, Ast *indice_ast) {
    Simbolo *s = buscar_simbolo(nome);
    int indice;
    char buffer[512];
    double valor;

    if (s == NULL) {
        printf("Erro semantico: vetor '%s' nao declarado.\n", nome);
        return;
    }

    if (!s->eh_vetor) {
        printf("Erro semantico: '%s' nao e vetor.\n", nome);
        return;
    }

    indice = indice_valido(s, indice_ast);
    if (indice < 0) {
        return;
    }

    printf("Digite valor para %s[%d]: ", nome, indice);

    if (s->tipo == DADO_TEXTO) {
        scanf(" %511[^\n]", buffer);
        free(s->str_vetor[indice]);
        s->str_vetor[indice] = duplicar_string(buffer);
    } else {
        scanf(" %lf", &valor);
        if (s->tipo == DADO_INTEIRO) {
            s->num_vetor[indice] = (int) valor;
        } else {
            s->num_vetor[indice] = valor;
        }
    }
}

int verdade(Valor v) {
    if (v.tipo == DADO_TEXTO) {
        return v.str != NULL && strlen(v.str) > 0;
    }
    return fabs(v.num) > 0.000001;
}

Valor eval(Ast *a) {
    Valor v1, v2;

    if (a == NULL) {
        return valor_num(0);
    }

    switch (a->tipo) {
        case NODE_NUM:
            return valor_num(a->valor);

        case NODE_STRING:
            return valor_str(a->texto);

        case NODE_BK:
            return valor_str("\n");

        case NODE_VAR_VALUE:
            return valor_variavel(a->nome);

        case NODE_ARRAY_VALUE:
            return valor_vetor(a->nome, a->esq);

        case NODE_SOMA:
            v1 = eval(a->esq);
            v2 = eval(a->dir);
            if (v1.tipo == DADO_TEXTO || v2.tipo == DADO_TEXTO) {
                printf("Erro semantico: soma aceita apenas numeros.\n");
                return valor_num(0);
            }
            return valor_num(v1.num + v2.num);

        case NODE_SUB:
            v1 = eval(a->esq);
            v2 = eval(a->dir);
            if (v1.tipo == DADO_TEXTO || v2.tipo == DADO_TEXTO) {
                printf("Erro semantico: subtracao aceita apenas numeros.\n");
                return valor_num(0);
            }
            return valor_num(v1.num - v2.num);

        case NODE_MULT:
            v1 = eval(a->esq);
            v2 = eval(a->dir);
            if (v1.tipo == DADO_TEXTO || v2.tipo == DADO_TEXTO) {
                printf("Erro semantico: multiplicacao aceita apenas numeros.\n");
                return valor_num(0);
            }
            return valor_num(v1.num * v2.num);

        case NODE_DIV:
            v1 = eval(a->esq);
            v2 = eval(a->dir);
            if (v1.tipo == DADO_TEXTO || v2.tipo == DADO_TEXTO) {
                printf("Erro semantico: divisao aceita apenas numeros.\n");
                return valor_num(0);
            }
            if (fabs(v2.num) < 0.000001) {
                printf("Erro semantico: divisao por zero.\n");
                return valor_num(0);
            }
            return valor_num(v1.num / v2.num);

        case NODE_POT:
            v1 = eval(a->esq);
            v2 = eval(a->dir);
            if (v1.tipo == DADO_TEXTO || v2.tipo == DADO_TEXTO) {
                printf("Erro semantico: potencia aceita apenas numeros.\n");
                return valor_num(0);
            }
            return valor_num(pow(v1.num, v2.num));

        case NODE_NEG:
            v1 = eval(a->esq);
            if (v1.tipo == DADO_TEXTO) {
                printf("Erro semantico: negativo aceita apenas numero.\n");
                return valor_num(0);
            }
            return valor_num(-v1.num);

        case NODE_MAIOR:
        case NODE_MENOR:
        case NODE_MAIOR_IGUAL:
        case NODE_MENOR_IGUAL:
        case NODE_IGUAL:
        case NODE_DIFERENTE:
            v1 = eval(a->esq);
            v2 = eval(a->dir);

            if (v1.tipo == DADO_TEXTO || v2.tipo == DADO_TEXTO) {
                if (a->tipo == NODE_IGUAL) {
                    return valor_num(strcmp(v1.str ? v1.str : "", v2.str ? v2.str : "") == 0);
                }
                if (a->tipo == NODE_DIFERENTE) {
                    return valor_num(strcmp(v1.str ? v1.str : "", v2.str ? v2.str : "") != 0);
                }
                printf("Erro semantico: textos so podem ser comparados com == ou !=.\n");
                return valor_num(0);
            }

            switch (a->tipo) {
                case NODE_MAIOR: return valor_num(v1.num > v2.num);
                case NODE_MENOR: return valor_num(v1.num < v2.num);
                case NODE_MAIOR_IGUAL: return valor_num(v1.num >= v2.num);
                case NODE_MENOR_IGUAL: return valor_num(v1.num <= v2.num);
                case NODE_IGUAL: return valor_num(fabs(v1.num - v2.num) < 0.000001);
                case NODE_DIFERENTE: return valor_num(fabs(v1.num - v2.num) >= 0.000001);
                default: return valor_num(0);
            }

        case NODE_AND:
            v1 = eval(a->esq);
            if (!verdade(v1)) {
                return valor_num(0);
            }
            v2 = eval(a->dir);
            return valor_num(verdade(v2));

        case NODE_OR:
            v1 = eval(a->esq);
            if (verdade(v1)) {
                return valor_num(1);
            }
            v2 = eval(a->dir);
            return valor_num(verdade(v2));

        case NODE_NOT:
            v1 = eval(a->esq);
            return valor_num(!verdade(v1));

        default:
            executar(a);
            return valor_num(0);
    }
}

void executar(Ast *a) {
    int contador;

    if (a == NULL) {
        return;
    }

    switch (a->tipo) {
        case NODE_BLOCK:
            executar(a->esq);
            executar(a->dir);
            break;

        case NODE_DECL:
            declarar_variavel(a->dado_tipo, a->nome);
            break;

        case NODE_DECL_ARRAY:
            declarar_vetor(a->dado_tipo, a->nome, a->esq);
            break;

        case NODE_ASSIGN:
            atribuir_variavel(a->nome, eval(a->esq));
            break;

        case NODE_ASSIGN_ARRAY:
            atribuir_vetor(a->nome, a->esq, eval(a->dir));
            break;

        case NODE_READ:
            ler_variavel(a->nome);
            break;

        case NODE_READ_ARRAY:
            ler_vetor(a->nome, a->esq);
            break;

        case NODE_PRINT:
            if (!print_itens(a->esq)) {
                printf("\n");
            }
            break;

        case NODE_IF:
            if (verdade(eval(a->esq))) {
                executar(a->dir);
            } else {
                executar(a->terceiro);
            }
            break;

        case NODE_WHEN:
            contador = 0;
            while (verdade(eval(a->esq))) {
                executar(a->dir);
                contador++;
                if (contador > 100000) {
                    printf("Erro semantico: repeticao when interrompida por limite de seguranca.\n");
                    break;
                }
            }
            break;

        case NODE_DO_WHEN:
            contador = 0;
            do {
                executar(a->esq);
                contador++;
                if (contador > 100000) {
                    printf("Erro semantico: repeticao do-when interrompida por limite de seguranca.\n");
                    break;
                }
            } while (verdade(eval(a->dir)));
            break;

        default:
            eval(a);
            break;
    }
}

int print_itens(Ast *a) {
    Valor v;

    if (a == NULL) {
        return 0;
    }

    if (a->tipo == NODE_PRINT_LIST) {
        print_itens(a->esq);
        return print_itens(a->dir);
    }

    if (a->tipo == NODE_BK) {
        printf("\n");
        return 1;
    }

    v = eval(a);

    if (v.tipo == DADO_TEXTO) {
        printf("%s", v.str ? v.str : "");
    } else {
        if (fabs(v.num - (int)v.num) < 0.000001) {
            printf("%d", (int)v.num);
        } else {
            printf("%f", v.num);
        }
    }

    return 0;
}

void liberar_ast(Ast *a) {
    if (a == NULL) {
        return;
    }

    liberar_ast(a->esq);
    liberar_ast(a->dir);
    liberar_ast(a->terceiro);
    free(a);
}

int main(int argc, char **argv) {
    if (argc > 1) {
        yyin = fopen(argv[1], "r");
    } else {
        yyin = fopen("programa1.dbe", "r");
    }

    if (yyin == NULL) {
        printf("Erro: nao foi possivel abrir o arquivo de entrada.\n");
        printf("Uso: ./analisador arquivo.dbe\n");
        return 1;
    }

    yyparse();
    fclose(yyin);

    return 0;
}
